import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTables1762942379909 implements MigrationInterface {
  name = 'CreateTables1762942379909';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`      CREATE TABLE "hotels" (
                              "hotel_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              "name" character varying(50) NOT NULL,
                              "location" character varying(75) NOT NULL,
                              "description" text,
                              "policy" text,
                              "stars" integer,
                              "created_at" TIMESTAMP NOT NULL DEFAULT now(),
                              "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
                              CONSTRAINT "UQ_hotels_name" UNIQUE ("name"),
                              CONSTRAINT "UQ_hotels_location" UNIQUE ("location"),
                              CONSTRAINT "PK_hotels_id" PRIMARY KEY ("hotel_id"),
                              CONSTRAINT "CHK_hotels_stars" CHECK ("stars" >= 1 AND "stars" <= 5)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "clients" (
                               "client_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               "first_name" character varying(50) NOT NULL,
                               "middle_name" character varying(50) NOT NULL,
                               "last_name" character varying(50) NOT NULL,
                               "phone" character varying(13) NOT NULL,
                               "email" character varying(100) NOT NULL,
                               "is_registered" boolean NOT NULL,
                               CONSTRAINT "UQ_clients_phone" UNIQUE ("phone"),
                               CONSTRAINT "UQ_clients_email" UNIQUE ("email"),
                               CONSTRAINT "PK_clients_id" PRIMARY KEY ("client_id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "employees" (
                                 "employee_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 "first_name" character varying(50) NOT NULL,
                                 "middle_name" character varying(50) NOT NULL,
                                 "last_name" character varying(50) NOT NULL,
                                 "phone" character varying(13) NOT NULL,
                                 "position" character varying(50) NOT NULL,
                                 "hotel_id" BIGINT,
                                 CONSTRAINT "UQ_employees_phone" UNIQUE ("phone"),
                                 CONSTRAINT "PK_employees_id" PRIMARY KEY ("employee_id"),
                                 CONSTRAINT "FK_employees_hotel" FOREIGN KEY ("hotel_id")
                                   REFERENCES "hotels"("hotel_id") ON DELETE CASCADE ON UPDATE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "rooms" (
                             "room_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             "room_number" integer NOT NULL,
                             "price_per_night" money NOT NULL,
                             "capacity" integer NOT NULL,
                             "comfort_level" character varying(20) NOT NULL,
                             "status" character varying(20) NOT NULL,
                             "hotel_id" BIGINT,
                             CONSTRAINT "UQ_rooms_room_number" UNIQUE ("room_number"),
                             CONSTRAINT "PK_rooms_id" PRIMARY KEY ("room_id"),
                             CONSTRAINT "FK_rooms_hotel" FOREIGN KEY ("hotel_id")
                               REFERENCES "hotels"("hotel_id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                             CONSTRAINT "CHK_rooms_comfort" CHECK ("comfort_level" IN ('luxury', 'comfort', 'premium', 'standard')),
                             CONSTRAINT "CHK_rooms_status" CHECK ("status" IN ('available', 'occupied', 'maintenance'))
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "bookings" (
                                "booking_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                "check_in" date NOT NULL,
                                "check_out" date NOT NULL,
                                "guests_count" integer NOT NULL,
                                "payment_method" character varying(50) NOT NULL,
                                "status" character varying(20) NOT NULL,
                                "cancel_reason" text,
                                "hotel_id" BIGINT,
                                "client_id" BIGINT,
                                "room_id" BIGINT,
                                CONSTRAINT "PK_bookings_id" PRIMARY KEY ("booking_id"),
                                CONSTRAINT "FK_bookings_hotel" FOREIGN KEY ("hotel_id")
                                  REFERENCES "hotels"("hotel_id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                                CONSTRAINT "FK_bookings_client" FOREIGN KEY ("client_id")
                                  REFERENCES "clients"("client_id") ON DELETE CASCADE ON UPDATE CASCADE,
                                CONSTRAINT "FK_bookings_room" FOREIGN KEY ("room_id")
                                  REFERENCES "rooms"("room_id") ON DELETE CASCADE ON UPDATE CASCADE,
                                CONSTRAINT "CHK_bookings_payment" CHECK ("payment_method" IN ('cash', 'credit-card', 'online')),
                                CONSTRAINT "CHK_bookings_status" CHECK ("status" IN ('confirmed', 'cancelled'))
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "payments" (
                                "payment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                "payment_date" date NOT NULL,
                                "method" character varying(20) NOT NULL,
                                "is_paid" boolean NOT NULL,
                                "amount" money NOT NULL,
                                "booking_id" BIGINT,
                                CONSTRAINT "PK_payments_id" PRIMARY KEY ("payment_id"),
                                CONSTRAINT "FK_payments_booking" FOREIGN KEY ("booking_id")
                                  REFERENCES "bookings"("booking_id") ON DELETE CASCADE ON UPDATE CASCADE,
                                CONSTRAINT "CHK_payments_method" CHECK ("method" IN ('online', 'cash', 'credit-card'))
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "services" (
                                "service_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                "service_name" character varying(50) NOT NULL,
                                "service_price" money NOT NULL,
                                "service_description" text,
                                "hotel_id" BIGINT,
                                CONSTRAINT "UQ_services_name" UNIQUE ("service_name"),
                                CONSTRAINT "PK_services_id" PRIMARY KEY ("service_id"),
                                CONSTRAINT "FK_services_hotel" FOREIGN KEY ("hotel_id")
                                  REFERENCES "hotels"("hotel_id") ON DELETE NO ACTION ON UPDATE NO ACTION
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "services"`);
    await queryRunner.query(`DROP TABLE "payments"`);
    await queryRunner.query(`DROP TABLE "bookings"`);
    await queryRunner.query(`DROP TABLE "rooms"`);
    await queryRunner.query(`DROP TABLE "employees"`);
    await queryRunner.query(`DROP TABLE "clients"`);
    await queryRunner.query(`DROP TABLE "hotels"`);
  }
}